@tool
extends RefCounted
## Generated by source/pack_tree_bark.gd; parts of the same surface; positions and colors preserved.
const MESHES := [
	preload("res://assets/garden_v1/models/tree_bark_00.res"),
	preload("res://assets/garden_v1/models/tree_bark_01.res"),
	preload("res://assets/garden_v1/models/tree_bark_02.res"),
	preload("res://assets/garden_v1/models/tree_bark_03.res"),
	preload("res://assets/garden_v1/models/tree_bark_04.res"),
	preload("res://assets/garden_v1/models/tree_bark_05.res"),
	preload("res://assets/garden_v1/models/tree_bark_06.res"),
]
