extends SceneTree
## Authoring utility: preserve every triangle, normal and color, in small native resources.
## Run after sculpt_tree_bark.py and Godot's GLB import.
const OUT := "res://assets/garden_v1/models/"
const TRIANGLES_PER_PART := 12000

func _initialize() -> void:
	var scene: PackedScene = load(OUT + "tree_bark.glb")
	var root := scene.instantiate()
	var node := root as MeshInstance3D
	if node == null: node = root.find_child("*", true, false) as MeshInstance3D
	var arrays := node.mesh.surface_get_arrays(0)
	var src_v: PackedVector3Array = arrays[Mesh.ARRAY_VERTEX]
	var src_n: PackedVector3Array = arrays[Mesh.ARRAY_NORMAL]
	var src_c: PackedColorArray = arrays[Mesh.ARRAY_COLOR]
	var src_i: PackedInt32Array = arrays[Mesh.ARRAY_INDEX]
	var paths: Array[String] = []
	var exact := true
	var max_position_error := 0.0
	var max_normal_error := 0.0
	var color_error := false
	for begin in range(0, src_i.size(), TRIANGLES_PER_PART * 3):
		var remap := {}
		var v := PackedVector3Array()
		var n := PackedVector3Array()
		var c := PackedColorArray()
		var idx := PackedInt32Array()
		for j in range(begin, mini(begin + TRIANGLES_PER_PART * 3, src_i.size())):
			var old := src_i[j]
			if not remap.has(old):
				remap[old] = v.size()
				v.append(src_v[old])
				n.append(src_n[old])
				c.append(src_c[old])
			idx.append(remap[old])
		var a := []
		a.resize(Mesh.ARRAY_MAX)
		a[Mesh.ARRAY_VERTEX] = v
		a[Mesh.ARRAY_NORMAL] = n
		a[Mesh.ARRAY_COLOR] = c
		a[Mesh.ARRAY_INDEX] = idx
		var mesh := ArrayMesh.new()
		mesh.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, a)
		var path := OUT + "tree_bark_%02d.res" % paths.size()
		var err := ResourceSaver.save(mesh, path, ResourceSaver.FLAG_COMPRESS)
		if err != OK:
			push_error("Bark resource save failed: " + path)
			quit(1)
			return
		# Verify the serialized bytes round-trip, using corresponding triangle corners.
		var saved: ArrayMesh = ResourceLoader.load(path, "ArrayMesh", ResourceLoader.CACHE_MODE_IGNORE)
		var back := saved.surface_get_arrays(0)
		for j in idx.size():
			var old := src_i[begin + j]
			var k: int = back[Mesh.ARRAY_INDEX][j]
			max_position_error = maxf(max_position_error, src_v[old].distance_to(back[Mesh.ARRAY_VERTEX][k]))
			max_normal_error = maxf(max_normal_error, src_n[old].distance_to(back[Mesh.ARRAY_NORMAL][k]))
			if src_c[old] != back[Mesh.ARRAY_COLOR][k]: color_error = true
		paths.append(path)
		print(path.get_file(), " ", FileAccess.get_file_as_bytes(path).size(), " bytes")
	var source := "@tool\nextends RefCounted\n## Generated by source/pack_tree_bark.gd; parts of the same surface; positions and colors preserved.\nconst MESHES := [\n"
	for path in paths: source += "\tpreload(\"" + path + "\"),\n"
	source += "]\n"
	var f := FileAccess.open(OUT + "bark_parts.gd", FileAccess.WRITE)
	f.store_string(source)
	f.close()
	root.free()
	exact = max_position_error < 0.000001 and max_normal_error < 0.0002 and not color_error
	print("BARK PACK: ", paths.size(), " parts; position error ", max_position_error, "; normal error ", max_normal_error, "; color changed ", color_error, "; parity passed ", exact)
	quit(0 if exact else 1)
